---
title: "datachallenge4"
author: "menglu zhao"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Monty Hall Simulation
```{r}
# if else statement to show which door is revealed 
door_to_reveal <- function(doors, prize_in_door, contestant_door) {
  if (prize_in_door == contestant_door) { # if the contestant's chosen door is the same as the prize door
    reveal <- sample(doors[-contestant_door], size = 1) # monty will reveal a goat from the remaining doors
  } else {
    reveal <- doors[-c(contestant_door, prize_in_door)] # monty will reveal the other door that has a goat
  }
  return(reveal)
}

# function that does one play of the Monty Hall simulation
play_monty_hall <- function(switch = FALSE) { # switch = false indicate the contestant does not want to switch doors
  doors <- 1:3 # three doors to choose from
  prize_door <- sample(doors, 1) # randomly assign the prize to a door
  contestant_door <- sample(doors, 1) # the door that contestant pick
  reveal <- door_to_reveal(doors, prize_door, contestant_door) # monty reveals a door which does not have the prize and was not picked by the contestant

  if (switch == TRUE) {
    contestant_door <- setdiff(doors, c(contestant_door, reveal))
  }
  return (contestant_door == prize_door)  # return a logical (TRUE/FALSE) indicating if the game was won or not
}

# simulation n times
simulate_monty_hall <- function(n, switch = FALSE) { 
  wins <- replicate(n, play_monty_hall(switch))
  mean(wins) # the proportion of wins
}

# test of the functions with 1000 plays
set.seed(123) 
without_switch <- simulate_monty_hall(1000, switch = FALSE)
with_switch <- simulate_monty_hall(1000, switch = TRUE)

without_switch * 100 # percentage of wining without switch
with_switch * 100 # percentage of wining with switch

```

